# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging
- docker tag udagram-api-feed pedroreck/udagram-api-feed:v1
- docker tag udagram-api-user pedroreck/udagram-api-user:v1
- docker tag udagram-frontend pedroreck/udagram-frontend:v1
- docker tag udagram-reverseproxy pedroreck/udagram-reverseproxy:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push pedroreck/udagram-api-feed:v1
- docker push pedroreck/udagram-api-user:v1
- docker push pedroreck/udagram-frontend:v1
- docker push pedroreck/udagram-reverseproxy:v1